### ISSUE TITLE
2023-08

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/test-actions#5]
```yml
Desc: ''
Source: ''
Tags: ''
Title: 「水坑」开发 Z-BlogPHP 应用时实现自动刷新网页_bilibili
Type: ''
Url: https://www.bilibili.com/video/BV1vTMeetEEo
```

**Comment by wdssmq** [comment]
```yml
Title: 「折腾」使用浏览器自带功能修改网站「响应标头」
Desc: 简要 有给各种网页写「GM_脚本」，姑且有弄「热重载」机制方便开发，但是一些网页的 CSP 策略不允许引入外部脚本，浏览器里也有临时禁用 CSP 的插件，但是并不总是管用，今天发现了一种浏览器自带的方法可以修改网站的「响应标头」，可以绕过网页自身的 CSP 限制；...
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: 折腾, 浏览器, GM_脚本
Type: 文章
Url: https://www.wdssmq.com/post/20120902324.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「言说」卡关人生
Desc: 剪了个视频投 B 站，回来就不想写了。。 我失败了 100 多次，最后通关了这个游戏关卡，然而人生中的各种事件同样…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: 游戏, 人生, 无力吐槽
Type: 文章
Url: https://www.wdssmq.com/post/20230102799.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「言说」2023 年仍然在纠结密码问题什么的
Desc: 前言 一直以来有一个纠结，正好在临开写前想到了如何概述这个纠结，那就是 —— 「实名过的小号还算不算小号这件事.j…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: 说点什么, 言说
Type: 文章
Url: https://www.wdssmq.com/post/20230102708.html

```

**Comment by wdssmq** [comment]
```yml
Title: WebDav 折腾「其一」
Desc: 既是前情提要，也是广告 之前图便宜买了台 NAT VPS，「1G RAM / 50GB Storage / EUR…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: WebDav, 网盘, 折腾
Type: 文章
Url: https://www.wdssmq.com/post/20100514969.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「Git_笔记」git remote 命令
Desc: 经常是先克隆了原始项目查看，然后发现需要作些修改，就需要 Fork 到自己账号下一份，所以要再修改一下远程仓库地址…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: Git_笔记, 折腾, Git
Type: 文章
Url: https://www.wdssmq.com/post/20220525683.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「Git_笔记」HEAD detached from xxxx 问题解决
Desc: 久违的想写个有点复杂的 Z-BlogPHP 插件，中间需要参考自己的其他项目，顺手改了下插件的一些格式排版，加了个…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: Git_笔记, 折腾, Git
Type: 文章
Url: https://www.wdssmq.com/post/20221127394.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「Git_笔记」Git Tag 操作汇总
Desc: 日常纠结之：本文内容是因为实际需要查找的资料汇总而成，所以过程中时临时存在哪里更合适呢.jpg 这一次是存在了 g…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: Git_笔记, 折腾, Git
Type: 文章
Url: https://www.wdssmq.com/post/20220407047.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「水坑」Z-BlogPHP 接口本质之「PHP 可变函数」
Desc: 一 严格来说，全部接口都是「监听」，监听接口本身被触发，然后执行指定的操作，或者对接口传递的数据进行处理。
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: GesF-Force, Z-BlogPHP, PHP
Type: 文章
Url: https://www.wdssmq.com/post/20220409155.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「水坑」略深入的讲解伪静态相关的知识
Desc: url 理论上指向的是一个文件，即使是目录也会按默认设置寻找 index.html 或 index.php，不存在…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: GesF-Force, Rewrite, PHP
Type: 文章
Url: https://www.wdssmq.com/post/20190704012.html


```

**Comment by wdssmq** [comment]
```yml
Title: 「水坑」Z-BlogPHP 模板机制讲解「简易版」
Desc: 例行中二时间 好像确实会不少东西，然而日常不知道有什么意义；...
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: GesF-Force, Z-BlogPHP, PHP
Type: 文章
Url: https://www.wdssmq.com/post/20201026266.html

```

**Comment by wdssmq** [comment]
```yml
Title: GitHub - wdssmq/snippets
Desc: VSCode 代码片段，Z-BlogPHP 为主
Image: null
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub, vscode, vscode-snippets, z-blogphp
Type: 代码
Url: https://github.com/wdssmq/snippets

```

**Comment by wdssmq** [comment]
```yml
Title: 「小代码」Z-BlogPHP 自用代码片段演示
Desc: 视频色调略奇怪；小红点控制鼠标的移动轨迹也略奇怪；
Image: null
Source: "[url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]"
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV1iv4y1K7iy

```

**Comment by wdssmq** [comment]
```yml
Title: 「小代码」Z-BlogPHP 插件开发之热重载演示（LiveReload）
Desc: 修改后自动刷新网页什么的……
Image: null
Source: "[url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]"
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV1eD4y147f3

```

**Comment by wdssmq** [comment]
```yml
Title: 「水坑」关于一个能用但是错误的正则表达式
Desc: 关于网上流传的「PHP 提取第一张图」中的正则表达式很多都是错的这件事
Image: null
Source: "[url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]"
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV1Z14y1V7MR

```

**Comment by wdssmq** [comment]
```yml
Title: 「小代码」rollup.js 开发「GM_脚本」演示
Desc: 关于录制过程比代码本身「大」（繁琐）了很多这件事.jpg 视频形式并不适合作为教程，只是演示；
Image: null
Source: "[url=https://space.bilibili.com/44744006]沉冰浮水@bilibili[/url]"
Tags: 哔哩哔哩
Type: 视频
Url: https://www.bilibili.com/video/BV1qe4y1d7ZM

```
