### ISSUE TITLE
2023-09

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/test-actions#6]
```yml
Title: 「言说」卡关人生
Desc: 剪了个视频投 B 站，回来就不想写了。。 我失败了 100 多次，最后通关了这个游戏关卡，然而人生中的各种事件同样…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: 游戏, 人生, 无力吐槽
Type: 文章
Url: https://www.wdssmq.com/post/20230102799.html

```

**Comment by wdssmq** [comment]
```yml
Title: 「言说」2023 年仍然在纠结密码问题什么的
Desc: 前言 一直以来有一个纠结，正好在临开写前想到了如何概述这个纠结，那就是 —— 「实名过的小号还算不算小号这件事.j…
Source: "[url=https://www.wdssmq.com]沉冰浮水的博客[/url]"
Tags: 说点什么, 言说
Type: 文章
Url: https://www.wdssmq.com/post/20230102708.html

```

**Comment by wdssmq** [comment]
```yml
Title: GitHub - wdssmq/GesF-Note
Desc: 用来记录各种折腾的东西，代码，文章或视频什么的丨大概可以理解为「咸鱼速报」…
Image: null
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub
Type: 代码
Url: https://github.com/wdssmq/GesF-Note

```

**Comment by wdssmq** [comment]
测试评论

**Comment by wdssmq** [comment]
```yml
Title: wdssmq/userscript
Desc: 各种「GM_脚本」
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub
Type: 代码
Url: https://github.com/wdssmq/userscript

```

**Comment by wdssmq** [comment]
```yml
Title: wdssmq/AI-Jumon
Desc: AI 提示词管理及构建工具，注重碎片化拼接及复用。
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub
Type: 代码
Url: https://github.com/wdssmq/AI-Jumon

```

**Comment by wdssmq** [comment]
```yml
Title: wdssmq/electron-demo
Desc: 研究 electron 的使用和开发；
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub
Type: 代码
Url: https://github.com/wdssmq/electron-demo

```

**Comment by wdssmq** [comment]
```yml
Title: GitHub - wdssmq/AI-Prompt-Generator
Desc: 一个基于 YAML 配置的 AI 提示词生成工具，支持变量替换和随机选择功能。
Source: "[url=https://github.com/wdssmq]wdssmq (沉冰浮水)@github[/url]"
Tags: GitHub
Type: 代码
Url: https://github.com/wdssmq/AI-Prompt-Generator

```
