### ISSUE TITLE
[申请收录]: 沉冰浮水 - wdssmq

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/test-actions#7]
### YML Data

```yml
# 前后的 源码块标记也要带上
name: 沉冰浮水
id: wdssmq
site:
    site_name: 沉冰浮水
    site_url: https://www.wdssmq.com/
    site_rss: https://www.wdssmq.com/feed.php
    site_desc: 置百丈玄冰而崩裂，掷须臾池水而漂摇。
app:
    - app_name: HelloZBlog
      app_desc: Z-BlogPHP 插件开发演示
      app_type: plugin
      app_url: https://github.com/wdssmq/HelloZBlog
    - app_name: Live2D-For-Z-BlogPHP
      app_desc: 适用于 Z-BlogPHP 的看板娘插件
      app_type: plugin
      app_url: https://github.com/wdssmq/Live2D-For-Z-BlogPHP
    # 可以有多个 app

```
